/**
 * render/entry — the throwaway Remotion entry point a programmatic render bundles.
 *
 * WHY THERE IS A GENERATED FILE AT ALL. `bundle()` takes a path to a module that
 * calls `registerRoot`, and webpack builds it in a separate process. The
 * composition this package compiles in-process is a live React component; there is
 * no way to hand one across that boundary, and any design that tried would be
 * inventing a serialisation format for closures.
 *
 * So nothing is handed across. The bundle is given the same JSON request and the
 * name of the same pack, and it runs the same template itself. Both sides compile
 * independently from identical inputs and arrive at identical output — which is
 * only true because `build` is pure and `RenderRequest` is JSON. The boundary that
 * looked like a constraint in `types.ts` is what makes this work.
 *
 * The in-process compile is therefore not redundant. It is how a bad request is
 * refused in milliseconds with real diagnostics, instead of ninety seconds later
 * as a webpack error, and it is where the resolved canvas comes from.
 *
 * WHAT IS INTERPOLATED. Two module specifiers and one request object. The
 * specifiers are paths this package computed or the caller supplied; the request
 * goes through `JSON.stringify`, so no caller-supplied value is ever spliced into
 * the source as code. A param containing a quote is a param, not an injection.
 */

import { type RenderRequest } from "./types";

export type EntrySpec = {
  /** Module exporting `createCompiler` — this package's root entry. */
  libModule: string;
  /** Module exporting the pack. */
  packModule: string;
  /** Named export to read from `packModule`. */
  packExport: string;
  /** The request, already validated in-process. */
  request: RenderRequest;
  /** The composition id the render will select. */
  compositionId: string;
  /** Stylesheet to pull into the bundle, or undefined for none. */
  stylesheet?: string;
};

/**
 * Import specifiers are emitted as JSON string literals rather than pasted between
 * quotes. A Windows path is full of backslashes, and `C:\temp\packs` spliced raw
 * into a string literal is `\t` and `\p` — one a tab, the other a syntax error.
 */
const literal = (value: string): string => JSON.stringify(value);

/**
 * Build the entry source.
 *
 * `registerRoot` receives a component that renders exactly one `Composition`. The
 * compile happens at module scope so a failure surfaces while the bundle is being
 * evaluated, not as an empty composition list at selection time.
 */
export const renderEntrySource = (spec: EntrySpec): string => {
  const { libModule, packModule, packExport, request, compositionId, stylesheet } = spec;

  return `// Generated by @shanairai/ai-studio for one render. Do not edit; it is deleted on completion.
import React from "react";
import { Composition, registerRoot } from "remotion";
${stylesheet === undefined ? "" : `// Tailwind emits CSS only for a stylesheet the bundle actually contains.\nimport ${literal(stylesheet)};\n`}
import { createCompiler } from ${literal(libModule)};
import { ${packExport} as pack } from ${literal(packModule)};

const request = ${JSON.stringify(compileRequestOf(request, compositionId), null, 2)};

const result = createCompiler(pack).compile(request);

if (!result.ok) {
  // The host process already compiled this same request successfully, so reaching
  // here means the two sides disagree — a different pack resolved, or a template
  // whose build is not pure. Both are worth failing loudly for.
  throw new Error(
    "ai-studio: the render bundle failed to compile a request the host accepted.\\n" +
      result.report.issues.map((i) => "  [" + i.code + "] " + i.stage + ": " + i.message).join("\\n"),
  );
}

const built = result.composition;

const Root = () => (
  React.createElement(Composition, {
    id: built.id,
    component: built.component,
    durationInFrames: built.durationInFrames,
    fps: built.fps,
    width: built.width,
    height: built.height,
  })
);

registerRoot(Root);
`;
};

/**
 * The compile request, as the bundle will see it.
 *
 * Render-only fields (`outputPath`, `codec`, `overwrite`, `version`) are dropped:
 * they say where the file goes and who may overwrite it, and the bundle neither
 * knows nor should know. What remains is the description of the picture, and it
 * must match the host's compile field for field — same id included, since the id
 * is what `selectComposition` looks up.
 */
const compileRequestOf = (request: RenderRequest, compositionId: string): Record<string, unknown> => ({
  id: compositionId,
  template: request.template,
  params: request.params ?? {},
  ...(request.brand !== undefined ? { brand: request.brand } : {}),
  ...(request.format !== undefined ? { format: request.format } : {}),
  ...(request.width !== undefined ? { width: request.width } : {}),
  ...(request.height !== undefined ? { height: request.height } : {}),
  ...(request.fps !== undefined ? { fps: request.fps } : {}),
  ...(request.duration !== undefined ? { duration: request.duration } : {}),
});

/** The same projection the host compiles, so the two sides cannot drift. */
export const hostCompileRequest = compileRequestOf;
