/**
 * jetset/manifest — what the Jet Set Adventures master film needs, and what we actually have.
 *
 * The single source of truth for readiness. Voiceover and brand marks are in place; every video
 * shot, the music bed and all nine sound-design cues are still outstanding. Music and SFX cannot
 * be generated by the connected tooling and must be licensed — each carries a `licence` field
 * that the verifier refuses to leave blank.
 *
 * Regenerate the report at any time with `npm run assets` (see `src/jetset/__tests__`).
 */

import { defineAssetManifest, type AssetRequirement } from "../manifest";

/** Commercial-use basis for the music bed, confirmed by the account holder on 2026-08-25. */
const ARTLIST_AI_LICENCE = "Artlist AI generation (Lyria 3 Pro, seed 02953) — commercial use confirmed by account holder";

/** Commercial-use basis for the generated sound design, verified against the provider terms. */
const ELEVENLABS_LICENCE = "ElevenLabs sound generation — commercial/advertising use permitted under paid plan terms";

const shot = (
  name: string,
  file: string,
  scene: string,
  purpose: string,
  durationSeconds: number,
): AssetRequirement => ({
  name,
  kind: "video",
  path: `jetset/video/${file}`,
  scene,
  purpose,
  durationSeconds,
  tolerance: 0.5,
  loops: false,
  cropPermitted: true,
  source: "generated",
  status: "present",
});

const voice = (name: string, file: string, scene: string, purpose: string, durationSeconds: number): AssetRequirement => ({
  name,
  kind: "voice",
  path: `jetset/audio/vo/${file}`,
  scene,
  purpose,
  durationSeconds,
  tolerance: 0.15,
  loops: false,
  cropPermitted: false,
  source: "generated",
  status: "present",
});

const bed = (name: string, file: string, scene: string, purpose: string, durationSeconds: number): AssetRequirement => ({
  name,
  kind: "ambience",
  path: `jetset/audio/ambience/${file}`,
  scene,
  purpose,
  durationSeconds,
  tolerance: 60,
  loops: true,
  cropPermitted: true,
  channels: 2,
  source: "generated",
  licence: ELEVENLABS_LICENCE,
  status: "present",
});

const hit = (name: string, file: string, scene: string, purpose: string, durationSeconds: number, channels: 1 | 2): AssetRequirement => ({
  name,
  kind: "sfx",
  path: `jetset/audio/sfx/${file}`,
  scene,
  purpose,
  durationSeconds,
  tolerance: 1.5,
  loops: false,
  cropPermitted: true,
  channels,
  source: "generated",
  licence: ELEVENLABS_LICENCE,
  status: "present",
});

export const jetSetManifest = defineAssetManifest({
  project: "Jet Set Adventures — 60s Master",
  requirements: [
    // --- brand (present) ---
    {
      name: "badge", kind: "image", path: "jetset/brand/logo.png", scene: "Act 7",
      purpose: "The circular badge logo, held on the navy endcard.",
      loops: false, cropPermitted: false, source: "owned", status: "present",
    },
    {
      name: "advisor", kind: "image", path: "jetset/brand/shanair-johnson.png", scene: "Act 7",
      purpose: "Shanair Johnson cutout, composited beside the badge on the endcard.",
      loops: false, cropPermitted: true, source: "owned", status: "present",
    },

    // --- picture (outstanding) ---
    shot("a1DeskExhale", "a1-desk-exhale.mp4", "Act 1", "Woman at a home desk stops typing and exhales — the ordinary-life hook.", 6),
    shot("a1HandStill", "a1-hand-still.mp4", "Act 1", "Insert: her hand goes still on the trackpad.", 4),
    shot("a1ReachPhone", "a1-reach-phone.mp4", "Act 1", "She turns to the window and picks up her phone — the decision beat.", 4),
    shot("a2BalconyDoors", "a2-balcony-doors.mp4", "Act 2", "Hero: balcony doors pushed open onto turquoise. The film's turn.", 6),
    shot("a2SandWalk", "a2-sand-walk.mp4", "Act 2", "Barefoot walk onto white sand into ankle-deep water.", 4),
    shot("a2YachtLaugh", "a2-yacht-laugh.mp4", "Act 2", "Friends laughing on a moving yacht deck.", 4),
    shot("a2Champagne", "a2-champagne.mp4", "Act 2", "Champagne poured and glasses touched over turquoise water.", 4),
    shot("a3AccraStreet", "a3-accra-street.mp4", "Act 3", "Traveller walking an Accra street market at golden hour.", 6),
    shot("a3FabricDetail", "a3-fabric-detail.mp4", "Act 3", "Hands adjusting a printed head-wrap in a tailor's mirror.", 4),
    shot("a3RooftopFood", "a3-rooftop-food.mp4", "Act 3", "Jollof and grilled fish set down on a rooftop table at dusk.", 4),
    shot("a3NightDance", "a3-night-dance.mp4", "Act 3", "Dancing under string lights to live drums.", 4),
    shot("a4HotelArrival", "a4-hotel-arrival.mp4", "Act 4", "Car door opens at a Dubai hotel; heel to marble, luggage rolling.", 6),
    shot("a4Skyline", "a4-skyline.mp4", "Act 4", "Blue-hour skyline from a high terrace, one figure at the rail.", 4),
    shot("a4RooftopDinner", "a4-rooftop-dinner.mp4", "Act 4", "Candlelit rooftop dinner, couple laughing, skyline behind.", 4),
    shot("a4Desert", "a4-desert.mp4", "Act 4", "4x4 cresting a dune ridge at sunset.", 4),
    shot("a5Arrivals", "a5-arrivals.mp4", "Act 5", "Girls trip: four friends striding out of arrivals into Miami sun.", 4),
    shot("a5PoolJump", "a5-pool-jump.mp4", "Act 5", "Mid-air jump into a rooftop pool.", 4),
    shot("a5Birthday", "a5-birthday.mp4", "Act 5", "Sparkler candle carried through a restaurant to cheering.", 4),
    shot("a5Boardwalk", "a5-boardwalk.mp4", "Act 5", "Couple hand in hand on a waterfront boardwalk at sunset.", 4),
    shot("a5NightOut", "a5-night-out.mp4", "Act 5", "Dancing in neon light, unguarded laughter.", 4),
    shot("a6BalconySunset", "a6-balcony-sunset.mp4", "Act 6", "Hero payoff: traveller alone on a balcony above a coastline at sunset.", 6),
    shot("a6FaceProfile", "a6-face-profile.mp4", "Act 6", "Slow push to her face in profile, a small private smile.", 6),
    shot("a7CoastPullback", "a7-coast-pullback.mp4", "Act 7", "Aerial pull-back over a coastline — the quiet bed under the endcard.", 8),

    // --- voiceover (present) ---
    voice("vo01Hook", "vo-01-hook.wav", "Act 1", "“When was the last time you went somewhere that made you feel alive?”", 4.22),
    voice("vo02Breathe", "vo-02-breathe.wav", "Act 2", "“Somewhere you could finally breathe.”", 4.4),
    voice("vo03Discover", "vo-03-discover.wav", "Act 3", "“Somewhere that shows you something new.”", 4.8),
    voice("vo04Live", "vo-04-live.wav", "Act 4", "“And somewhere that reminds you what living actually feels like.”", 6.08),
    voice("vo05Occasions", "vo-05-occasions.wav", "Act 5", "“Girls trip. Birthday. Anniversary. Adventure.”", 3.2),
    voice("vo06OrMaybe", "vo-06-ormaybe.wav", "Act 5", "“Or maybe…”", 2.28),
    voice("vo07JustBecause", "vo-07-justbecause.wav", "Act 6", "“Just because.” — lands as the picture slows.", 2.28),
    voice("vo08NoWait", "vo-08-nowait.wav", "unused", "Recorded but cut from the master for timing. Kept for reinstatement.", 4.8),
    voice("vo09NextStory", "vo-09-nextstory.wav", "Act 6", "“Your next story is waiting.” — the campaign line.", 4.0),
    voice("vo10Signoff", "vo-10-signoff.wav", "Act 7", "“Jet Set Adventures. Let’s go somewhere unforgettable.”", 5.68),

    // --- music (SUPPLIED: Igor Vitte, "Malibu", licensed for video by Artlist) ---
    {
      name: "musicBed", kind: "music", path: "jetset/audio/music/bed-afrobeat-lyria-02953.wav", scene: "whole film",
      purpose: "Uplifting Afrobeat/Reggae bed. Selected from eight auditions against the locked picture; its arrangement releases across the 45.92s payoff and recovers to full level for the endcard.",
      durationSeconds: 86.44, tolerance: 0.5, loops: false, cropPermitted: true, channels: 2,
      source: "generated", licence: ARTLIST_AI_LICENCE, status: "present",
    },

    // --- ambience beds (delivered, LOOP) ---
    // Paths are the asset key, matching what the acquisition layer writes. The earlier
    // descriptive names here never existed on disk and would have failed at render.
    bed("ambRoomTone", "ambRoomTone.wav", "Act 1", "Quiet domestic interior. Makes the room feel small.", 12),
    bed("ambOcean", "ambOcean.wav", "Act 2", "Ocean wash. J-cut: arrives 0.6s BEFORE the picture.", 14),
    bed("ambAccra", "ambAccra.wav", "Act 3", "Accra street life, no music. J-cut: leads its picture by 0.4s.", 14),
    bed("ambBalconyWind", "ambBalconyWind.wav", "Acts 6-7", "Wind and distant surf. L-cut: carries under the payoff and endcard.", 18),

    // --- one-shot sound design (delivered) ---
    // All four are stereo: the sound-generation endpoint delivers stereo regardless of request.
    hit("sfxPhoneTap", "sfxPhoneTap.wav", "Act 1", "Soft phone haptic on the decision beat. Felt, not heard.", 0.48, 2),
    hit("sfxWhoosh", "sfxWhoosh.wav", "Act 1→2", "Low airy whoosh that makes the smash cut physical.", 1.48, 2),
    hit("sfxLuggage", "sfxLuggage.wav", "Act 4", "Rolling luggage on polished marble. Sells the scale.", 3.0, 2),
    hit("sfxSplash", "sfxSplash.wav", "Act 5", "One clean body-into-water impact, landing on the beat.", 2.0, 2),
  ],
});
